/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;
import com.istloja.controlador.Inventariosbd;
import com.istloja.modelTables.ModelTableInventarios;
//import javax.swing.JFrame;

/**
 *
 * @author ANDRES
 */
public class BusquedaAvanzada extends javax.swing.JDialog {

    /**
     * Creates new form BusquedaAvanzada
     */
    private ModelTableInventarios modelTableInventarios;
    private Inventariosbd controladorInventarios;
    
    public BusquedaAvanzada(java.awt.Frame parent, boolean modal, ModelTableInventarios 
            modelTableInventarios, Inventariosbd controladorInventarios) {
        super(parent, modal);
        this.modelTableInventarios = modelTableInventarios;
        this.controladorInventarios = controladorInventarios;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxBusquedaAvanzada = new javax.swing.JComboBox<>();
        txtBusquedaAvanzada = new javax.swing.JTextField();
        btnBusquedaA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Busqueda");

        cbxBusquedaAvanzada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbxBusquedaAvanzada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar:", "Codigo", "Descripción" }));

        btnBusquedaA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBusquedaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/resource/img/buscar.png"))); // NOI18N
        btnBusquedaA.setText("Buscar");
        btnBusquedaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaAActionPerformed(evt);
            }
        });

        jTable1.setModel(modelTableInventarios);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(cbxBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBusquedaA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusquedaA))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaAActionPerformed
        // TODO add your handling code here:
        System.out.println("Combo" +cbxBusquedaAvanzada.getSelectedIndex());
        switch (cbxBusquedaAvanzada.getSelectedIndex()){
            case 0:
                modelTableInventarios.fireTableDataChanged();
            case 1: //CODIGO
                modelTableInventarios.setInventarios(controladorInventarios.buscarInvetarioCodigoCombo
                (txtBusquedaAvanzada.getText()));
                modelTableInventarios.fireTableDataChanged();
                break; 
            case 2: //DESCRIPCION
                modelTableInventarios.setInventarios(controladorInventarios.buscarInvetarioDescripcionCombo
                (txtBusquedaAvanzada.getText()));
                modelTableInventarios.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBusquedaAActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaA;
    private javax.swing.JComboBox<String> cbxBusquedaAvanzada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusquedaAvanzada;
    // End of variables declaration//GEN-END:variables
}
